common:
  api_key: xyz123
  origins: http://localhost:3000

elasticsearch:
  host: http://ozdb:9200
  username: 
  password: 
  verify: false
  ca_cert: 
  cert_bundle: 
  indexes:
     - semantic-python-index_enriched
     - semantic-elastic-co-index_enriched
     - semantic-wikipedia-index_enriched

